### ISSUE TITLE
Error: nmp run start

### ISSUE THREAD

**Issue by starinajes** [Harrix/static-site-webpack-habr#7]
Запускаем webpack dev server: 

Получаем ошибку

`
internal/modules/cjs/loader.js:883
  throw err;
  ^
Error: Cannot find module 'webpack-cli/bin/config-yargs'

  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '...../node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
`

Как я понимаю, в package.json вместо 
` webpack-dev-server --mode development --open `
надо 
` webpack serve `

**Comment by Harrix** [comment]
Спасибо! Всё верно. Поправил в коммите https://github.com/Harrix/static-site-webpack-habr/commit/511971f32f067faf428b312573ea1915cb5b89be
